config/routes.rb
NonScaffoldedRails::Application.routes.draw do

  get "posts/index"

  root :to => 'info#index'

  match 'about' => 'info#about', :as => 'about'

  match 'contact_us' => 'info#contact_us', :as => 'contact'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title, :content, :presence => true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
 #although these controller actions are all empty
 #we create here such that it is obvious which views exist
 #three routes have been defined for these actions in the congif.route.rb file
	def index
	end#automatically loads:index.html

	def about
	end#loads: about.html.erb

	def contact_us
	end#loads: contact_us.
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	#Route defined for this index action, the URL being /posts 
  def index
  	@posts = Post.all
  end
  #after this index action executes Rails will load the index.html.erb
  def show
  	@post = Post.find(params[:id])
  end#auto load the show.html.erb

  def new
  	@post = Post.new
  end#load the new.html.erb

  def create
  	#Create a new post object with the data the user submitted from the new view form 
  	@post = Post.new(params[:post])
  	#validation pass we redirect to the index action
  	if (@post.save)
  		redirect_to :action => :index
  	#validation fails we reuse the view associated 
  	else
  		render :action => :new
  	end 
  end#only loads a view on error otheriwse reads direct

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to :action => :index
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
      @post = Post.find(params[:id])
      @post.update_attributes(params[:post])
      if @post.save
        redirect_to :action => :index
      else
        render :action => :edit
      end 
    
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/info/about.html.erb
<h2>About</h2>

<p>
Blah blah blah some content goes here about whatever
</p>

app/views/info/contact_us.html.erb
<h2>Contact Us</h2>

<p>
contach us wherever you want blah blah blah 
</p>

app/views/info/index.html.erb
<h2>Home Page</h2>

<p>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NonScaffoldedRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p>
	<%= image_tag 'rails.png' %>
</p>

<div id="menu">
	<ul>
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'About', about_path %></li>
		<li><%= link_to 'Contact Us', contact_path %></li>
		<li><%= link_to 'Company Blog', posts_path %></li>
	</ul>
</div>
<!--this is where our views are injected -->
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Update Post</h2>
<!-- the F block param is known as a form nuilder. 
	use it to build the elments of our form.. -->
<%= form_for @post do |f| %>
	<div>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :content%><br>
		<%= f.text_area :content%>
	</div>
	<div>
		<%= f.submit 'Update post' %>
	</div>
<% end %>

app/views/posts/index.html.erb
<h2>Company Blog</h2>


<% @posts.each  do |post| %>
	<h3><%= link_to post.title, post %></h3>
	<p><%= post.created_at %><p>
	<p><%= post.content %></p>
	<p>
		<%= link_to 'Delete', post, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
		<%= link_to 'Edit', edit_post_path(post) %>
	</p>
<% end %>

<p>
	<%= link_to 'Create New Blog Post', new_post_path %>
</p>

app/views/posts/new.html.erb
<h2>Create a new Post</h2>
<!-- the F block param is known as a form nuilder. 
	use it to build the elments of our form.. -->
<%= form_for @post do |f| %>
	<div>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :content%><br>
		<%= f.text_area :content%>
	</div>
	<div>
		<%= f.submit 'Submit New post' %>
	</div>
<% end %>

app/views/posts/show.html.erb
<h2>Company Blog</h2>
<h3><%= @post.title %></h3>
<p><%= @post.created_at %><p>
<p><%= @post.content %></p>